### ISSUE TITLE
More clarity / better examples for function tag 

### ISSUE THREAD

**Issue by webketje** [eemeli/yaml-types#10]
Hi there, really like this stuff but I'm struggling to find the correct way to implement a function tag, and also to understand what to expect it to return upon parsing. I did:

```js
import { parse } from 'yaml'
import { functionTag } from 'yaml-types'

parse('!function function() { console.log("hello") }', { customTypes: [functionTag] } )
```
but I get:
```js
YAMLParseError: Unexpected token 'u', "function() "... is not valid JSON at line 1, column 1:

!function function() {console.log("hello")}
^^^^^^^^^

    at async ModuleLoader.import (https://stackblitzstartersy2f5yt-xb4h.w-corp-staticblitz.com/builtins.ddb8d84d.js:154:2688)
    at async loadESM (https://stackblitzstartersy2f5yt-xb4h.w-corp-staticblitz.com/builtins.ddb8d84d.js:184:541)
    at async handleMainPromise (https://stackblitzstartersy2f5yt-xb4h.w-corp-staticblitz.com/builtins.ddb8d84d.js:165:296) {
  code: 'TAG_RESOLVE_FAILED',
  pos: [ 0, 9 ],
  linePos: [ { line: 1, col: 1 }, { line: 1, col: 10 } ]
}
```
even though parseDocument().schema shows that the function tag is loaded.
It's unclear to me what is supported here as input to `parse`:
```js
'\'!function() {console.log("hello")}\''
'!function function() {console.log("hello")}'
'!function () => {console.log("hello")}'
'!function arg => console.log("hello")}'
```

The function tag docblock says:
```js
 * When parsing, a no-op function with matching name and toString() is
 * returned. It is not possible to construct an actual JavaScript function by
 * evaluating YAML, and it is unsafe to attempt.
 */
exports.functionTag = {
    identify: value => typeof value === 'function',
    tag: '!function',
```
so I'm also not really sure what to expect (regexp obviously parses as regexp), a string of the function, a noop function?
 I'm not a YAML expert like you but it's also not clear to me when and why a tag is prefixed with 2 vs 1 exclamation mark

**Comment by eemeli** [comment]
A couple of things:
1. It's `customTags`, not `customTypes`.
2. The serialized representation of functions isn't the same as their JS source representation, as it needs to represent the function name separately:
   ```js
   import { stringify } from 'yaml'
   stringify(function foo() { console.log("hello") }, { customTags: [functionTag] } )
   ```
   ```yaml
   !function |-
   "foo"
   function foo() { console.log("hello") }
   ```
3. It's intentional that the resulting function is not built by evaluating the source contents, as that would not be safe.
4. In YAML, local/custom tags use one `!`, default tags use two `!!`.

**Comment by webketje** [comment]
Thank you! The snippet you shared IMO is valuable for documentation, I don't think I found any such example, and I understand much better now. All JS fn syntaxes are (potentially) supported, given that the evaluation is left up to the user of this library; you can kind of get the answer by looking at https://github.com/eemeli/yaml-types/blob/main/src/function.test.ts for different types of input

> It's intentional that the resulting function is not built by evaluating the source contents, as that would not be safe.

This can be done like below using a "post-parse" eval (tossing safety concerns aside) and is the thing I was interested in:

```js
const src = `!function |-
  "(anonymous)"
  function() {console.log("hello")}'`

let helloworldFn;
eval('helloworldFn = ' +  YAML.parse(src,  {  customTags: [functionTag] }).toString());
helloworldFn();
```

**Comment by BurtHarris** [comment]
YAML is not designed to serialize functions. It is a data language, and functions are not included in [the standard](https://yaml.org/spec/1.2.2/) for security reasons. Using JavaScript's eval() function has previously led to significant security breaches. Although the provided example might work, using YAML for data definition and writing code in your application to interpret this data is better practice. 

Documentation of this approach is not advisable, as this is a common mistake for junior programmers. YAML is, however, a good way to create a "domain-specific language " tailored to a specific task and not procedural in nature. 

The security risk associated with using eval() or similar functions is called [mobile code](https://csrc.nist.gov/glossary/term/mobile_code) vulnerabilities. For more information,, see [Eval is Evil](https://dev.to/amitkhonde/eval-is-evil-why-we-should-not-use-eval-in-javascript-1lbh).

**Comment by BurtHarris** [comment]
Additional references:  

- https://www.oreilly.com/library/view/javascript-the-good/9780596517748/apcs21.html *
- https://www.digitalocean.com/community/tutorials/js-eval
- https://www.educative.io/courses/building-safer-javascript-applications/the-eval-function
- https://nedbatchelder.com/blog/201206/eval_really_is_dangerous.html

In addition to the security risks, using `eval()` in modern JS engines can severely impact performance.


\* Douglas Crockford's book [JavaScript: The Good Parts](https://www.oreilly.com/library/view/javascript-the-good/9780596517748/) is probably the best reading on Javascript for anyone using the language.  ***Don't encourage others to use the bad parts of JavaScript!***  [Crockford invented JSON!](https://www.json.org/json-en.html) He is deeply knowledgeable and a great writer.  The YAML authors updated the YAML specification to make it a superset of JSON.

**Comment by webketje** [comment]
@BurtHarris I know all this and I am not a junior programmer. Tell me what your usage would be of the `yaml-types` `!function` tag (and others, for that matter), and what the point of your comments is. Or is this a troll ChatGPT copy-paste.
